ci(tests): update organization secret

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -157,6 +157,34 @@ jobs:
         run: echo "::error::Expected HTTP status code 204 got
           ${{steps.self.outputs.status}}"; exit 1
 
+  test_organization:
+    name: test organization secret
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
+
+      - name: Download build artifact
+        uses: actions/download-artifact@v2
+        with:
+          name: main
+          path: dist
+
+      - name: Update a secret
+        id: self
+        uses: ./
+        with:
+          location: deinopon
+          name: TEST_CREATE_GITHUB_SECRET_ACTION
+          value: ${{ github.sha }}
+          pa_token: ${{ secrets.PA_TOKEN_ORG_ADMIN }}
+
+      - name: Assert action output
+        if: steps.self.outputs.status != '201'
+        run: echo "::error::Expected HTTP status code 201 got
+          ${{steps.self.outputs.status}}"; exit 1
+
   release:
     name: release new version
     if: contains(fromJson('["refs/heads/master","refs/heads/next"]'),
@@ -166,6 +194,7 @@ jobs:
       - test_create
       - test_repo_location
       - test_update
+      - test_organization
     steps:
       - name: Checkout repository
         uses: actions/checkout@v2
